#!/bin/bash

if [[ -z $DISALLOWED_CODE ]]; then
  source $SERVER_HOME/webapp.sh
  if [[ -z $DISALLOWED_CODE ]]; then
    echo "DISALLOWED_CODE is undefined."
    exit 1
  else
    #we had to source nozomi.sh in the commit, which is a waste because
    #then it has to happen for each commit.
    echo "Please source $SERVER_HOME/setup/webapp.sh in your shell to avoid sourcing it automatically for each commit."
  fi
fi

files=$(git diff --cached --name-only --diff-filter=ACM | grep -v "webapp.sh" | grep -v "Gemfile")
if [ "$files" = "" ]; then
    exit 0
fi

pass=true

for file in ${files}; do
    result=$(ag "debugger|byebug|logger.*#{params}" -G "js$|rb$" --ignore=pre-commit)

    if [[ "$result" != "" ]]; then
      echo -e "${file} contains disallowed code: $result"
      pass=false
    fi
done

if ! $pass; then
  echo -e "\e[103m\e[1m\e[31m\e[5mCommit cancelled due to disallowed code.\e[0m"
  exit 1
else
  exit 0
fi
